spring:
  application:
    name: To-Do-Service
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://database-1.ct6jcofgybfx.us-east-1.rds.amazonaws.com:3306/hr
    username: sourabh
    password: Sourabh123
    
server:
  port: 5000
  
management:
  endpoints:
    web:
      exposure:
        include:
        - '*'